site_name: Mohamed Metwalli
nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Skills: skills.md
  - Education: education.md
  - Contact: contact.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/metwalli
    - icon: fontawesome/brands/github
      link: https://github.com/mtwalli
