name: Site
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: site
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: https://mtwalli.github.io/site/
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        shell: bash
      - uses: actions/cache@v4.2.0
        with:
          key: mkdocs-material-${{env.cache_id}}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build Site
        run: |
          mkdocs build --clean
          mkdocs --version
      
      - name: Upload Site to GitHub Pages
        id: upload_pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site
          retention-days: 1

      - name: Deploy Site to GitHub Pages
        uses: actions/deploy-pages@v4.0.5